import type { Event } from "./types"

export const mockEvents: Event[] = [
  {
    id: "EVT-001",
    timestamp: "2023-04-03T10:15:30Z",
    source: "192.168.1.100",
    destination: "admin.company.com",
    type: "Authentication",
    subtype: "Failed Login",
    severity: "medium",
    confidence: 85,
    details: "Failed login attempt for user admin@company.com. Invalid password.",
    user: "admin@company.com",
    hostname: "DC-01",
    protocol: "HTTPS",
    application: "Admin Portal",
    country: "Russia",
    department: "IT",
    tags: ["Brute Force", "Authentication Failure"],
  },
  {
    id: "EVT-002",
    timestamp: "2023-04-03T10:16:45Z",
    source: "192.168.1.100",
    destination: "admin.company.com",
    type: "Authentication",
    subtype: "Failed Login",
    severity: "medium",
    confidence: 85,
    details: "Failed login attempt for user admin@company.com. Invalid password.",
    user: "admin@company.com",
    hostname: "DC-01",
    protocol: "HTTPS",
    application: "Admin Portal",
    country: "Russia",
    department: "IT",
    tags: ["Brute Force", "Authentication Failure"],
  },
  {
    id: "EVT-003",
    timestamp: "2023-04-03T10:18:12Z",
    source: "192.168.1.100",
    destination: "admin.company.com",
    type: "Authentication",
    subtype: "Successful Login",
    severity: "low",
    confidence: 90,
    details: "Successful login for user admin@company.com.",
    user: "admin@company.com",
    hostname: "DC-01",
    protocol: "HTTPS",
    application: "Admin Portal",
    country: "Russia",
    department: "IT",
    tags: ["Successful Authentication"],
  },
  {
    id: "EVT-004",
    timestamp: "2023-04-03T10:20:05Z",
    source: "admin.company.com",
    destination: "db.company.internal",
    type: "Database",
    subtype: "Query",
    severity: "high",
    confidence: 75,
    details: "SELECT * FROM customer_records WHERE credit_card IS NOT NULL",
    user: "db_service",
    hostname: "DB-01",
    protocol: "SQL",
    application: "Database Server",
    country: "United States",
    department: "IT",
    tags: ["Sensitive Data Access", "Database Query"],
  },
  {
    id: "EVT-005",
    timestamp: "2023-04-03T10:22:30Z",
    source: "admin.company.com",
    destination: "192.168.1.100",
    type: "Data",
    subtype: "Exfiltration",
    severity: "critical",
    confidence: 95,
    details: "Large data transfer (25MB) to external IP address.",
    user: "admin@company.com",
    hostname: "DC-01",
    protocol: "HTTPS",
    application: "Admin Portal",
    country: "Russia",
    department: "IT",
    tags: ["Data Exfiltration", "Large Transfer"],
  },
  {
    id: "EVT-006",
    timestamp: "2023-04-03T11:05:15Z",
    source: "mail.external.com",
    destination: "user@company.com",
    type: "Email",
    subtype: "Phishing",
    severity: "high",
    confidence: 88,
    details: "Suspected phishing email with malicious attachment.",
    user: "user@company.com",
    hostname: "MAIL-01",
    protocol: "SMTP",
    application: "Email Server",
    country: "United Kingdom",
    department: "Marketing",
    tags: ["Phishing", "Malicious Attachment"],
  },
  {
    id: "EVT-007",
    timestamp: "2023-04-03T11:30:45Z",
    source: "ws-045.company.internal",
    destination: "multiple",
    type: "Network",
    subtype: "Port Scan",
    severity: "medium",
    confidence: 82,
    details: "Internal host scanning multiple ports on network.",
    user: "jane.smith",
    hostname: "WS-045",
    protocol: "TCP",
    application: "Unknown",
    country: "United States",
    department: "Finance",
    tags: ["Port Scan", "Internal Threat"],
  },
  {
    id: "EVT-008",
    timestamp: "2023-04-03T12:15:20Z",
    source: "ws-045.company.internal",
    destination: "file-server.company.internal",
    type: "File",
    subtype: "Modification",
    severity: "high",
    confidence: 91,
    details: "Multiple files encrypted with .locked extension.",
    user: "jane.smith",
    hostname: "WS-045",
    protocol: "SMB",
    application: "File Server",
    country: "United States",
    department: "Finance",
    tags: ["Ransomware", "File Modification"],
  },
]
